import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import { ShieldAlert, CheckCircle, Activity, BrainCircuit, ArrowLeft, Info, AlertTriangle, FileText, X } from 'lucide-react';
import {
  Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer,
  BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, Legend, Cell
} from 'recharts';
import './SimilarityAnalysis.css';

export default function SimilarityAnalysis() {
  const { id } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const [loading, setLoading] = useState(true);
  const [selectedCase, setSelectedCase] = useState(null);
  
  const { resultInfo, patientData } = location.state || {
    resultInfo: { type: 'Fallback', diagnosis: 'Sample High Similarity: Mucormycosis', percentage: 92 },
    patientData: { symptoms: 'N/A' }
  };

  const isHighRisk = resultInfo.percentage > 70;
  
  // Generate dynamic chart data based on result type
  const mockRadarData = [
    { subject: 'Necrosis', A: resultInfo.type === 'Mucormycosis' ? 95 : 20, B: 65, fullMark: 100 },
    { subject: 'Fever', A: resultInfo.type === 'General' ? 50 : 85, B: 75, fullMark: 100 },
    { subject: 'Vision Loss', A: resultInfo.type === 'Mucormycosis' ? 88 : 10, B: 30, fullMark: 100 },
    { subject: 'Swelling', A: resultInfo.type === 'Mucormycosis' ? 90 : (resultInfo.type === 'Oncology' ? 70 : 40), B: 80, fullMark: 100 },
    { subject: 'Lesions/Tumor', A: resultInfo.type === 'Oncology' ? 95 : 30, B: 40, fullMark: 100 },
  ];

  const mockBarData = [
    { name: 'Dataset Alpha (Oncology)', Similarity: resultInfo.type === 'Oncology' ? resultInfo.percentage : 15, color: '#8b5cf6' },
    { name: 'Dataset Beta (General)', Similarity: resultInfo.type === 'General' ? resultInfo.percentage : 30, color: '#94a3b8' },
    { name: 'Dataset Gamma (Mucormycosis)', Similarity: resultInfo.type === 'Mucormycosis' ? resultInfo.percentage : 12, color: '#f43f5e' },
    { name: 'Dataset Delta (Viral)', Similarity: 28, color: '#10b981' },
  ];

  // Simulate complex AI calculation rendering
  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1500);
    return () => clearTimeout(timer);
  }, []);

  // Mock Clinical Matches
  const mockMatches = [
    { 
      name: "P. R. Sharma", age: 52, gender: "Male", match: 94.2, symptom: "Palatal Necrosis", hospital: "AIIMS Delhi", date: "Oct 2023",
      refId: "NHI-DL-9921",
      history: "Patient presented with blackish discoloration of palate 3 weeks post-COVID recovery. History of uncontrolled diabetes.",
      treatment: "Debridement surgery followed by Amphotericin B liposomal (5mg/kg/day).",
      outcome: "Recurrence prevented, sinus clear at 6-month follow-up."
    },
    { 
      name: "A. K. Verma", age: 48, gender: "Male", match: 89.5, symptom: "Orbital Swelling", hospital: "Tata Memorial", date: "Jan 2024",
      refId: "TMH-MB-4412",
      history: "Unilateral eye swelling and headache. Early CT showed mucosal thickening in the ethmoid sinus.",
      treatment: "Endoscopic Sinus Surgery (ESS) and aggressive antifungal therapy.",
      outcome: "Vision preserved, patient in stable remission."
    },
    { 
      name: "S. Subramaniam", age: 61, gender: "Female", match: 82.1, symptom: "Vision Blur", hospital: "Apollo Hospitals", date: "Mar 2024",
      refId: "APL-CH-1209",
      history: "Sudden onset vision loss in left eye. Previously treated with high-dose steroids for pulmonary complications.",
      treatment: "Retrobulbar injections and intravenous antifungal protocol.",
      outcome: "Significant recovery of peripheral vision after 12-week intensive cycle."
    }
  ];

  if (loading) {
// ... existing loading screen ...
    return (
      <div className="loading-screen">
        <BrainCircuit size={64} className="icon-pulse text-primary" />
        <h2>Generating Deep Inference Report...</h2>
        <p className="text-muted">Comparing patient vector space against 14.2M records</p>
      </div>
    );
  }

  return (
    <div className="analysis-page animate-fade-in">
      <div className="analysis-header">
        <button className="btn-ghost back-btn" onClick={() => navigate('/dashboard')}>
          <ArrowLeft size={18} /> Back
        </button>
        <div>
          <h1>Analysis Report: <span className="text-gradient">{id}</span></h1>
          <p className="text-muted">Generated by NeuralMatch v2.4 Classification Engine</p>
        </div>
      </div>

      <div className="results-grid">
        <div className="main-result glass-panel">
          <div className={`result-alert ${isHighRisk ? 'danger-alert' : 'warning-alert'} fade-in-up`}>
            {isHighRisk ? <ShieldAlert size={48} color="var(--danger)" /> : <Info size={48} color="var(--primary)" />}
            <div>
              <h3 style={{color: isHighRisk ? 'var(--danger)' : 'var(--primary)'}}>
                {isHighRisk ? 'High Similarity Detected: ' : 'Analysis Result: '}
                {resultInfo.diagnosis}
              </h3>
              <p>The patient's symptom clustering ({patientData.symptoms}) and imaging data show a {resultInfo.percentage}% match with historical {resultInfo.type} cases.</p>
            </div>
            <div className="match-score">
              <span className="score" style={{color: isHighRisk ? 'var(--danger)' : 'var(--primary)'}}>{resultInfo.percentage}</span>
              <span className="percent" style={{color: isHighRisk ? 'var(--danger)' : 'var(--primary)'}}>%</span>
            </div>
          </div>
          
          <div className="chart-container">
            <h3>Symptom Vector Comparison</h3>
            <div className="radar-wrapper">
              <ResponsiveContainer width="100%" height={300}>
                <RadarChart cx="50%" cy="50%" outerRadius="80%" data={mockRadarData}>
                  <PolarGrid stroke="rgba(255,255,255,0.1)" />
                  <PolarAngleAxis dataKey="subject" tick={{ fill: '#94a3b8', fontSize: 12 }} />
                  <PolarRadiusAxis angle={30} domain={[0, 100]} stroke="rgba(255,255,255,0.1)" />
                  <Radar name="Current Case" dataKey="A" stroke="#f43f5e" fill="#f43f5e" fillOpacity={0.5} />
                  <Radar name="Baseline Average" dataKey="B" stroke="#0ea5e9" fill="#0ea5e9" fillOpacity={0.3} />
                  <Legend />
                </RadarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        <div className="side-results">
          <div className="glass-panel stats-card">
            <h3>Dataset Cross-Reference</h3>
            <p className="text-sm text-muted mb-4">Similarity indices across medical dataset categories.</p>
            
            <div className="bar-wrapper">
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={mockBarData} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" horizontal={false} />
                  <XAxis type="number" stroke="rgba(255,255,255,0.2)" domain={[0, 100]} />
                  <YAxis dataKey="name" type="category" width={100} tick={{ fill: '#94a3b8', fontSize: 10 }} stroke="none" />
                  <Tooltip 
                    contentStyle={{ backgroundColor: 'rgba(15, 23, 42, 0.9)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: '#fff' }}
                    itemStyle={{ color: '#fff' }}
                  />
                  <Bar dataKey="Similarity" radius={[0, 4, 4, 0]}>
                    {mockBarData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="glass-panel recommendation-card">
            <div className="section-title">
              {isHighRisk ? <AlertTriangle size={20} color="var(--warning)" /> : <CheckCircle size={20} color="var(--success)" />}
              <h3>{isHighRisk ? 'Critical Action Required' : 'Recommended Action'}</h3>
            </div>
            <ul className="action-list">
              {resultInfo.type === 'Mucormycosis' && (
                <>
                  <li>Immediate consultation in infectious diseases department.</li>
                  <li>Schedule comprehensive MRI paranasal sinuses.</li>
                  <li>Hold immunosuppressant therapy pending biopsy.</li>
                </>
              )}
              {resultInfo.type === 'Oncology' && (
                <>
                  <li>Referral to Oncology for comprehensive biopsy.</li>
                  <li>Initiate PET scan for metastasis evaluation.</li>
                  <li>Assign dedicated tumor board review.</li>
                </>
              )}
              {resultInfo.type === 'General' && (
                <>
                  <li>Monitor vitals continuously over next 48 hours.</li>
                  <li>Standard broad-spectrum care based on physician inference.</li>
                  <li>Awaiting further lab pathology results.</li>
                </>
              )}
            </ul>
            <button className="btn-primary w-full mt-4">Download PDF Report</button>
          </div>
        </div>
      </div>

      <div className="matches-section">
        <div className="section-header-row">
          <Activity size={24} color="var(--primary)" />
          <h2>Top Clinical Cohort Matches</h2>
          <p className="text-muted">Anonymized patient profiles with highest vector similarity.</p>
        </div>
        
        <div className="matches-grid">
          {mockMatches.map((match, idx) => (
            <div key={idx} className="match-card glass-panel animate-fade-in" style={{animationDelay: `${idx * 0.2}s`}}>
              <div className="card-accent-bar"></div>
              <div className="match-card-header">
                <div className="match-avatar">
                  {match.gender === 'Male' ? 'M' : 'F'}
                </div>
                <div className="match-identity">
                  <div className="ref-badge">{match.refId}</div>
                  <h4>{match.name}</h4>
                  <span>Age: {match.age} • {match.gender}</span>
                </div>
                <div className="match-percentage-badge">
                  <Activity size={12} />
                  {match.match}% Match
                </div>
              </div>
              <div className="match-card-body">
                <div className="clinical-preview">
                  <label>Primary Diagnosis/Symptom</label>
                  <p>{match.symptom}</p>
                </div>
                <div className="meta-info-grid">
                  <div className="meta-item">
                    <label>Inference Source</label>
                    <span>{match.hospital}</span>
                  </div>
                  <div className="meta-item">
                    <label>Archived Date</label>
                    <span>{match.date}</span>
                  </div>
                </div>
              </div>
              <button 
                className="btn-primary-sm w-full mt-4"
                onClick={() => setSelectedCase(match)}
              >
                Access Clinical Study
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Case Study Modal */}
      {selectedCase && (
        <div className="modal-overlay animate-fade-in" onClick={() => setSelectedCase(null)}>
          <div className="case-modal glass-panel" onClick={e => e.stopPropagation()}>
            <button className="modal-close" onClick={() => setSelectedCase(null)}>
              <X size={20} />
            </button>
            
            <div className="modal-header">
              <div className="case-icon">
                <FileText size={24} color="var(--primary)" />
              </div>
              <div>
                <h2>Clinical Case Study: {selectedCase.name}</h2>
                <p className="text-sm text-dim">Reference: AI-COHORT-{Math.floor(Math.random() * 9000) + 1000}</p>
              </div>
            </div>

            <div className="modal-content">
              <div className="case-overview-grid">
                <div className="case-stat">
                  <label>Similarity Score</label>
                  <span className="text-emerald">{selectedCase.match}%</span>
                </div>
                <div className="case-stat">
                  <label>Age/Gender</label>
                  <span>{selectedCase.age}y / {selectedCase.gender}</span>
                </div>
              </div>

              <div className="case-detail-block">
                <h3><Info size={16} /> Clinical History</h3>
                <p>{selectedCase.history}</p>
              </div>

              <div className="case-detail-block">
                <h3><Activity size={16} /> Treatment Protocol</h3>
                <p>{selectedCase.treatment}</p>
              </div>

              <div className="case-detail-block">
                <h3><CheckCircle size={16} /> Outcome & Prognosis</h3>
                <p>{selectedCase.outcome}</p>
              </div>
            </div>

            <button className="btn-primary w-full mt-6" onClick={() => setSelectedCase(null)}>
              Close Case Study
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
